### ISSUE TITLE
Add testing integration, PyPI release, and conda-forge package

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/Theano-PyMC#11]
In order to release we should have integration testing (I think theano used travis), as well as an upload to PyPI and a conda-forge package.

**Comment by brandonwillard** [comment]
Should we consider moving the unit tests (currently in [Travis](https://travis-ci.org/github/pymc-devs/Theano-PyMC)) to GitHub Actions when/if we consider performing deployments via Actions?  @dfm, any opinion on this?

**Comment by canyon289** [comment]
Theres a decent chance I'll try moving testing to AzureCI this weekend but if someone beats me to it please go ahead

**Comment by canyon289** [comment]
Just to be clear I'm not opinated on one or another, but I personally prefer azure pipelines as I was going to copy the pipelines from ArviZ and tweak them a bit. Either is fine, it just sounds like whoever starts this and gets to the end first will make the choice :D

https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-azure-pipelines-to-github-actions#:~:text=GitHub%20Actions%20uses%20YAML%20files,not%20support%20a%20graphical%20editor.&text=Azure%20Pipelines%20supports%20stages%20defined,into%20separate%20YAML%20workflow%20files.

**Comment by brandonwillard** [comment]
I'm not a fan of the context shift implied by Azure, at least not without more motivating advantages.  In general, the tight integration of GitHub Actions with&mdash;well&mdash;GitHub is difficult to beat.

**Comment by canyon289** [comment]
Cool, I'll defer to you then since I wont be spending a lot of time in this repo. Glad you commented here! :)

**Comment by brandonwillard** [comment]
We should probably change the "testing integration" in this title to "GPU-enabled CI".  Currently, that's the big missing test piece.

**Comment by twiecki** [comment]
We have all of these now. I'll add a separate issue for GPU.
