### ISSUE TITLE
CI should fail on new uncovered lines

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#118]
We need to set up our CI/Coveralls to fail on newly introduced uncovered lines&mdash;at the very least!

**Comment by OriolAbril** [comment]
I know how to do this with codecov, not with coveralls though which is what is currently used. I could set codecov up with github actions if it seems easier to do this than with coveralls or if there is interest in switching.

**Comment by brandonwillard** [comment]
I'm fine using either.  @dfm what's your opinion?

**Comment by dfm** [comment]
I don't have strong opinions either way! Coveralls is currently set to fail for coverage decreases of 2% or more, but we could change that back to 0%. There is no option for exactly what you want as far as I know.

**Comment by brandonwillard** [comment]
My experience with the percent metric is that it has been always been difficult to justify and deal with, especially across multiple runs.  Plus, it's not good if one can increase coverage for unrelated code while not covering new code and still pass the acceptance threshold.

If Codecov provides better metrics, then I'm all for it.  The only requirement is that it works with CI in the same way that @dfm currently has it working (i.e. that it works with parallel jobs and checks the aggregate result in a single, separate Action step)

**Comment by dfm** [comment]
That all sounds reasonable. I'm sure it's easy enough to get codecov working in this mode, but I don't have experience with the specific features it offers. Happy to take a shot at it next week or review a pull request!

**Comment by dfm** [comment]
The only step of the workflow that would need to be changed is the final step where the combined coverage is uploaded. The other steps are not coveralls specific.
