### ISSUE TITLE
Issue with JAX-ifying ops with multiple outputs

### ISSUE THREAD

**Issue by dfm** [pymc-devs/Theano-PyMC#165]
There seems to be an issue with the jaxifying logic when treating nodes with multiple outputs. I haven't dug too much, but I found this for an op I'm working on for https://github.com/dfm/exoplanet. It was easy to reproduce using `MaxAndArgmax` which was the only op implemented in `sandbox.jaxify` that has multiple outputs (as far as I can tell). The following code will throw the relevant error:

```python
import theano
import numpy as np

x = theano.tensor.dvector()
mx, amx = theano.tensor.MaxAndArgmax([0])(x)
result = mx + amx

fgraph = theano.gof.FunctionGraph([x], [result])
opts = theano.gof.Query(include=[None], exclude=["cxx_only", "BlasOpt"])
jax_mode = theano.compile.mode.Mode(theano.sandbox.jax_linker.JAXLinker(), opts)
py_mode = theano.compile.Mode("py", opts)

theano_jax_fn = theano.function(fgraph.inputs, fgraph.outputs, mode=jax_mode)
theano_jax_fn(np.random.randn(10))
```

This results in a long error message which ends with:

```python
~/miniconda3/envs/exoplanet/lib/python3.8/site-packages/theano/sandbox/jaxify.py in <listcomp>(.0)
    153         def jax_func(*inputs):
--> 154             func_args = [fn(*inputs) for fn in input_funcs]
    155             return return_func(*func_args)

FilteredStackTrace: TypeError: 'list' object is not callable
```

cc @junpenglao

**Comment by brandonwillard** [comment]
There are more `Op`s with multiple outputs: see [`test_jax_basic_multiout`](https://github.com/pymc-devs/Theano-PyMC/blob/99f08ee3307b6084e204fa8327824af62e51b39a/tests/sandbox/test_jax.py#L252).

**Comment by dfm** [comment]
@brandonwillard: good point. Those work because the outputs are not being used together as inputs lower in the graph. If I run those tests, they pass. But, if I replace the first one, for example, with:

```python
outs = tt.nlinalg.eig(x)
out_fg = theano.gof.FunctionGraph([x], [tt.sum(outs[0]) + tt.sum(outs[1])])
```

I get the same error.

**Comment by brandonwillard** [comment]
Yeah, I think I know what's causing it; I'll set up a PR.
