### ISSUE TITLE
Ensure that there's only one evaluation of a multi-output JAXified `Op`

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#170]
@brandonwillard: One question about this implementation because I'm not sure that I fully understand everything that's happening: Will this lead (on the JAX side) to the function being evaluated multiple times, once for each output? I'm not sure that I know enough about the JAX implementation details to know!

_Originally posted by @dfm in https://github.com/pymc-devs/Theano-PyMC/issues/166#issuecomment-728091044_

**Comment by brandonwillard** [comment]
Answering the question here: It might be evaluated more than once, but that also depends on what the JAX tracing does.  There's only one function created and used for a given call, but the #166 does [call it separately for each output](https://github.com/brandonwillard/Theano-PyMC/blob/459f1f2d0b0e7e233cf5b8eaf83409c26775ab54/theano/sandbox/jaxify.py#L164).

We could cache a single thunk for the `out_fn(*inputs)` expression itself and turn `jax_multiout_func` into an index-index only operation on that cached result.  That seems like the most direct way to ensure only one evaluation.

**Comment by dfm** [comment]
I can confirm that, when `jit`-ed the multiple calls seem to be optimized out. The function is *traced* multiple times but only actually evaluated once.

**Comment by brandonwillard** [comment]
Perfect!  I really didn't want to add something for that.

**Comment by brandonwillard** [comment]
@dfm, is there a good way to make a unit test for that?

**Comment by dfm** [comment]
Hmm. I'm not too sure. Since I'm writing my own XLA calls I could just add a print statement but I'm not sure how easy it would be to formally test. I'll think about it.
