### ISSUE TITLE
Many failures when jit-ing JAX-ified ops

### ISSUE THREAD

**Issue by dfm** [pymc-devs/Theano-PyMC#177]
If we turn on `jax.jit` in the JAX tests

<details>
<summary>See diff</summary>

```diff
diff --git a/tests/sandbox/test_jax.py b/tests/sandbox/test_jax.py
index 89c46ff9b..eb51e82ed 100644
--- a/tests/sandbox/test_jax.py
+++ b/tests/sandbox/test_jax.py
@@ -56,7 +56,7 @@ def compare_jax_and_py(
     py_mode = theano.compile.Mode("py", opts)

     theano_jax_fn = theano.function(fgraph.inputs, fgraph.outputs, mode=jax_mode)
-    jax_res = theano_jax_fn(*inputs)
+    jax_res = jax.jit(theano_jax_fn)(*inputs)

     if must_be_device_array:
         if isinstance(jax_res, list):
```
</details>

most of the unit tests fail with errors related to calling numpy functions on JAX trace objects. This will be a huge problem (JAX isn't all that useful without `jit`!) so we should definitely be testing for and supporting this.

Am I missing something here?

**Comment by junpenglao** [comment]
theano_jax_fn is already jitted.

**Comment by dfm** [comment]
haha - womp :D
