### ISSUE TITLE
IfElse JAX conversion should use cond

### ISSUE THREAD

**Issue by dfm** [pymc-devs/Theano-PyMC#178]
Related to #177:

The current implementation of the JAX translation for the IfElse op is going to be problematic [because of how JAX handles control flow when `jit`-ing](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Control-Flow). We should probably be using [`jax.lax.cond`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cond.html) instead.

**Comment by eigenfoo** [comment]
I'd be interested in taking this on.

To clarify, we'd want to change

https://github.com/pymc-devs/Theano-PyMC/blob/a9275c3dcc998c8cca5719037e493809b23422ff/theano/sandbox/jaxify.py#L530-L536

to be something like

```python
def ifelse(cond, *args, n_outs=n_outs):
    res = jax.lax.cond(cond, lambda: args[:n_out], lambda: args[n_out:])
    return res if n_outs > 1 else res[0]
```

Is that right? Also, how can we test the jit-friendliness of the new `IfElse` implementation?

**Comment by eigenfoo** [comment]
Actually, using that function fails the corresponding test:

```
E       TypeError: true_fun and false_fun output must have same type structure, got PyTreeDef(tuple, [*]) and *.
E       Apply node that caused the error: if{}(TensorConstant{True}, TensorConstant{[1 2 3]}, TensorConstant{[-1 -2 -3]})
E       Toposort index: 0
E       Inputs types: [TensorType(bool, scalar), TensorType(int64, vector), TensorType(int64, vector)]
E       Inputs shapes: []
E       Inputs strides: []
E       Inputs values: []
E       Outputs clients: [['output']]
```

The problem is the "unwrapping" of the `res` object on line 536 - the if and else branch need to return the same type. Can we do anything about this?

**Comment by dfm** [comment]
@eigenfoo: I'm not too sure what the right answer is. Theano and JAX are differently strict about the conditions required for control flow like this so we might always run into some issues.

But, I think that [the current tests only touch cases where the argument of the conditional is a constant](https://github.com/pymc-devs/Theano-PyMC/blob/master/tests/sandbox/test_jax.py#L463-L478). A good place to start would be adding a test where this is a traceable tensor. I expect that this will fail then we can start figuring out how to fix it!

**Comment by eigenfoo** [comment]
Sorry for my ignorance - what do you mean by a "traceable tensor"?

**Comment by dfm** [comment]
Haha! Just a tensor 😀. Like

tt.dscalar() < 0.5, for example.

**Comment by brandonwillard** [comment]
> @dfm sorry for my ignorance - what do you mean by a "traceable tensor"?

From what I've seen, `jax` just "traces" the function it's JITing by&mdash;for example&mdash;performing calls on a wrapped version of said function with `mock`-like arguments that are essentially symbolic arrays: these are the "traced" arrays.  Through this process it builds what amounts to a symbolic graph, and, as it descends into inner functions of the outer-most JITed function, it creates more traced arrays.  

This tracing approach is a somewhat easy way to make the graph stuff look like normal Python at the user-level, but it also has some real drawbacks.
