### ISSUE TITLE
Cannot access Theano documentation

### ISSUE THREAD

**Issue by Sayam753** [pymc-devs/Theano-PyMC#189]
I just went to http://www.deeplearning.net/software/theano for theano documentation and it gives 404 error. Is this because of changes in Theano-PyMC?

**Comment by twiecki** [comment]
Probably not, but we should start thinking aobut hosting our own docs.

**Comment by dfm** [comment]
https://theano-pymc.readthedocs.io is current and connected to this repo AFAIK.

**Comment by Sayam753** [comment]
That's great @dfm. Thanks. 
@twiecki can you update the about section of this repo with correct docs link?

**Comment by Sayam753** [comment]
@dfm there are still internal links that point back to original theano repo. I was trying to access Cholesky decomposition `source` from https://theano-pymc.readthedocs.io/en/latest/library/tensor/slinalg.html, but it took me to original theano.

**Comment by dfm** [comment]
Yeah - I can't vouch for the details of the docs! New docstrings are included and it's built using the source in this repo, but I don't think anyone has worked on auditing the documentation itself. I was just saying that the readthedocs.io version wouldn't be *worse* than the deeplearning.net ones...

This particular comment is probably related to this:

https://github.com/pymc-devs/Theano-PyMC/blob/0c203e994fc33c5a5a00cfa184bc43d9c9cd7f4b/doc/conf.py#L228

And a full audit of the documentation would be awesome!

**Comment by Sayam753** [comment]
Many thanks @dfm for clarification. For now, I will close the issue since I have access to theano documentation.
I agree on fixing the internal links and that can be tracked in separate issue/PR.
