### ISSUE TITLE
Finish removing old Python 2.x compatibility code

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#24]
There's still a lot of unnecessary code for Python 2.x compatibility that needs to be removed.  For instances, it seems like the entire `theano.compat` module could be removed.

**Comment by eigenfoo** [comment]
I'd be interested in taking this on.

@brandonwillard asides from removing the `theano.compat` module and any references to it, what other compat code should I look to remove/fix? Here's a short list I found by `rg`ing for the usual suspects (`"python2"`, `"compat"`, etc.). Please feel free to add/change.

- [ ] A few one-liners
  * https://github.com/pymc-devs/Theano-PyMC/blob/3767f231e73721395c6736d7f1f1ded4a0ec11e9/theano/gradient.py#L1938
  * https://github.com/pymc-devs/Theano-PyMC/blob/044f52eca91901da637b50513a5cc86091439879/tests/unittest_tools.py#L282
- [ ] Canopy
  * https://github.com/pymc-devs/Theano-PyMC/blob/2e3f17cbcf1462972c7a0074a8c34568dd8f4fa1/theano/gof/cmodule.py#L1707-L1712
- [ ] There are some references to Python 2 in the `doc/` directory, but I assume we don't really care about that?

**Comment by brandonwillard** [comment]
All of the above!

Regarding `cmp` and `DefaultOrderedDict`, we can move those to a `utils.py`&mdash;that seems to fit the pattern of our sub-packages.  Ultimately, we should refactor code that uses things like `cmp`, when possible.

Otherwise, there are also a few remaining uses of the old `%` string interpolation operator that we should convert to `str.format`&mdash;or we could convert everything to f-strings.  Either way, we want to be consistent.
