### ISSUE TITLE
Failing PyMC3 tests: with ValueError: Trying to rebroadcast non-existent dimension

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/Theano-PyMC#243]
From https://github.com/pymc-devs/pymc3/pull/4382:
```
self = <theano.compile.ops.Rebroadcast object at 0x7faa084385b0>, x = normal_rv.out

    def make_node(self, x):
        if self.axis.keys() and (x.ndim <= max(self.axis.keys())):
>           raise ValueError("Trying to rebroadcast non-existent dimension")
E           ValueError: Trying to rebroadcast non-existent dimension

Theano-PyMC/theano/compile/ops.py:719: ValueError
[...]
FAILED pymc3/tests/test_sampling.py::TestSample::test_sample_init - ValueError: Trying to rebroadcast non-existent dimension
FAILED pymc3/tests/test_sampling.py::test_exec_nuts_init[advi] - ValueError: Trying to rebroadcast non-existent dimension
FAILED pymc3/tests/test_variational_inference.py::test_replacements_in_sample_node_aevb[NormalizingFlowGroup: {'flow': 'scale'}] - ValueError: Trying to rebroadcast non-existent dimension
[...]
```

**Comment by michaelosthege** [comment]
This is a severe digression.

We can't cut a release unless this is fixed.

**Comment by michaelosthege** [comment]
Just making some notes here:

| Theano version | PyMC version | Result |
| - | - | - |
| abc69153 | b7daf266 | ✔️ *not 100 % compatible, but the bug is not yet there* |
| ... | ... | ... |
| 50c60b6b | 4d1e01b5 | ❌ Trying to rebroadcast non-existent axis |

**Comment by brandonwillard** [comment]
Is this an issue for a _feature branch/PR_?

**Comment by michaelosthege** [comment]
> Is this an issue for a _feature branch/PR_?

Yes - the PR that attempts to restore compatibility.. Maybe it should not switch the RNG ? I'm not familiar with this stuff

**Comment by brandonwillard** [comment]
First, it's rather odd to have an issue in this repo for a PR in a different repo, especially when it's not even clear whether or not the underlying issue is due to something in this repo.  This is all stuff that's well contained within the PR itself.

**Comment by brandonwillard** [comment]
I've looked over this PR and `pymc3.variational` code that's failing is simply calling `tt.patternbroadcast` with inconsistent arguments, so there's no sign of a Theano-PyMC bug&mdash;yet, at least.

Let's continue working on this in the PR; otherwise, there will be too much unnecessary back-and-forth.
