### ISSUE TITLE
Beta and Kumaraswamy distributions break the Jax Sampling (numpyro_nuts/sample_tfp_nuts)

### ISSUE THREAD

**Issue by luke14free** [pymc-devs/Theano-PyMC#249]
I am fully aware that this is 100% experimental but wanted to report that using any beta distribution in your model will break jax sampling.

**Please provide a minimal, self-contained, and reproducible example.**
```python
import pymc3 as pm
import pymc3.sampling_jax

with pm.Model() as hierarchical_model:
    b = pm.Beta('beta', 0.2, 0.2) # same with Kumaraswamy
    trace_jax = pm.sampling_jax.sample_numpyro_nuts(2000, tune=2000, target_accept=0.9) # same with sample_tfp_nuts
```

**Please provide the full traceback.**
```python
...
~/.local/share/virtualenvs/luca-J6Q-PZUv/lib/python3.7/site-packages/theano/sandbox/jaxify.py in jax_funcify_ScalarOp(op)
    182 @jax_funcify.register(ScalarOp)
    183 def jax_funcify_ScalarOp(op):
--> 184     func_name = op.nfunc_spec[0]
    185 
    186     if "." in func_name:
AttributeError: 'Second' object has no attribute 'nfunc_spec'
```

Requires the master of [Theano-PyMC](https://github.com/pymc-devs/Theano-PyMC), as well as JAX, TFP-nightly and numpyro.

## Versions and main components

* PyMC3 Version: v3.10.0
* Theano Version: 1.0.11
* Python Version: 3.7.5
* Operating system: osx 11.1
* How did you install PyMC3: pip

**Comment by twiecki** [comment]
No idea what `nfunc_spec` does. @luke14free do you think that's the right fix? Want to do a PR?

**Comment by luke14free** [comment]
Not really.. Ideally`jax_funcify_ScalarOp` should be agnostic on what function passed does.

So what I am thinking is that the `jax_funcify_ScalarOp` should somehow leverage the take function from numpy to get the -1th element (with a limit of 2 arguments). Will keep you posted, but the PR should be for theano-pymc.

**Comment by twiecki** [comment]
@luke14free OK, keep me posted. I moved the issue over.

**Comment by dfm** [comment]
This was fixed in #185, I believe.

**Comment by luke14free** [comment]
I see that 185 solves the specific case; I was wondering what happens to the other functions which are non-jaxable (i.e. have no direct translation from numpy) though.

What about something like this?

```
@jax_funcify.register(ScalarOp)
def jax_funcify_ScalarOp(op):
    if not hasattr(op, 'nfunc_spec'):
        return op.impl
```

**Comment by dfm** [comment]
I don't think that specific recommendation would work, since `impl` operates on numpy arrays, not JAX tensors. Do you have other examples of ops that are not currently supported? It's not hard to add the special cases.

**Comment by luke14free** [comment]
Ah now it makes a lot of sense now. Well this should solve it and I will just try to install theano-pymc from git to have the latest version! thanks a lot!!

**Comment by twiecki** [comment]
Note that there are still some incompatibilities between theano and pymc3 master.
