### ISSUE TITLE
Issue with softplus approximation

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/Theano-PyMC#260]
The current implemenation of softplus (aka log1pexp) uses two bounds to decide whether to return `0, log1p(exp(x)), or x`

https://github.com/pymc-devs/Theano-PyMC/blob/511c778f8a595444e009bcad738d552413b16f2c/theano/tensor/nnet/sigm.py#L356-L366

So far so good (almost). However, different bounds are used for the `c_code` depending on the precision being used https://github.com/pymc-devs/Theano-PyMC/blob/511c778f8a595444e009bcad738d552413b16f2c/theano/tensor/nnet/sigm.py#L376-L400

Unless I am missing something there might be an issue with both of the upper bounds used in the `c_code` (`14.0f and 16.0`). 

According to [Machler, 2012](https://cran.r-project.org/web/packages/Rmpfr/vignettes/log1mexp-note.pdf) who describes a refined method for `log1pexp` there is unnecessary error in using the approximation `log1pexp = x` for values of x < 33.3 (green line in Figure 3).

![image](https://user-images.githubusercontent.com/28983449/103476628-d7cfb600-4db7-11eb-8772-5b70592c6a27.png)

I don't know why the upper bounds are so low. It seems like `log1p(exp(x))` shouldn't overflow so soon. Using the code mentioned in the comment I get overflow only at +89 for float32 and at +710 for float64. This makes me very confident that the reason for choosing these was computational speed, but according to Machler (2012) a safer cutoff would have been 33.3, or an equally good intermediate approximation `x + exp(-x)` could be used until 33.3.

***

For reference here is the entire Machler (2012) suggestion, which tries to achieve a good compromise between speed and numerical precision for the entire real range:

```python
    if x <= -37.0: 
        return exp(x)
    elif x <= 18.0:
        return log1p(exp(x))
    elif x <= 33.3:
        return x + exp(-x)
    else:
        return x   
```
Plus the current appropriate lower bounds in `c_code` to return 0 instead of underflowing when x is very negative.

The changes are:
1. Using the approximation `exp(x)` for values below -37, instead of the current approach of returning `0` for values below 30 in `Theano` or the more costly `log1p(exp(x))` for any values that don't underflow in `c`.
2. Using the approximation `x + exp(-x)` in the range [18, 33.3] instead of the more costly (according to Machler and, it seems, the Theano guys as well) `log1p(exp(x))`
3. Using the approximation `x` only when it is no worse than `log1p(exp(x))` or `x + exp(-x)`, which occurs at 33.3 (again according to Machler).

**Comment by twiecki** [comment]
Thanks for the thorough investigation. I think going with the paper's suggestion is the way to go here, as we really don't know where those original bounds come from and they seem to have some problems. Want to make a PR?

**Comment by ricardoV94** [comment]
I can give it a try @twiecki
