### ISSUE TITLE
tt.switch behaves surprisingly with homogenous non boolean input

### ISSUE THREAD

**Issue by ricardoV94** [pymc-devs/Theano-PyMC#270]
```python
print(tt.switch(np.ones(10), 0, 1).eval())
print(tt.switch(np.ones(10).astype(bool), 0, 1).eval())

[0]
[0 0 0 0 0 0 0 0 0 0]
```
However it works fine with non-boolean inputs, as long as they are not all the same.
```python
a = np.ones(10)
a[0] = 0
print(tt.switch(a, 0, 1).eval())

[1 0 0 0 0 0 0 0 0 0]
```
This was behind a subtle bug in the Bernoulli distribution of PyMC (https://github.com/pymc-devs/pymc3/issues/4389), which seems to have been there since pymc3's inception...

**Comment by brandonwillard** [comment]
What's the corresponding behavior in NumPy?

**Comment by ricardoV94** [comment]
What would be the equivalent function to `tt.switch`?

**Comment by brandonwillard** [comment]
`numpy.where`, I believe.

**Comment by ricardoV94** [comment]
Seems to work as expected.

```python
np.where(np.ones(10), 0, 1)    
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
```

**Comment by ricardoV94** [comment]
In case it was not clear. This is "surprising", because it works fine with non homogenous array input. I updated the first post to highlight this.

**Comment by brandonwillard** [comment]
Yes, if the behavior doesn't match the corresponding NumPy function (if there is one), then it's definitely a bug.
