### ISSUE TITLE
Beta often diverges when logodds is close to 19.0

### ISSUE THREAD

**Issue by bridgeland** [pymc-devs/Theano-PyMC#29]
## Description 

This simple model never diverges in NUTS:

```python
import numpy as np
import pymc3 as pm

with pm.Model() as good_model:
    good_beta = pm.Beta('good_beta', alpha=0.25, beta=3.0, shape=40)

with good_model:
    good_trace = pm.sample(draws=600, chains=2, tune=500) 
```

But this very similar model---with alpha and beta swapped---diverges on about half the samples:

```python
import numpy as np
import pymc3 as pm

with pm.Model() as bad_model:
    bad_beta = pm.Beta('bad_beta', alpha=3.0, beta=0.25, shape=40)

with bad_model:
    bad_trace = pm.sample(draws=600, chains=2, tune=500)
```

```python
Sampling 2 chains for 500 tune and 600 draw iterations (1_000 + 1_200 draws total) took 17 seconds.
There were 328 divergences after tuning. Increase `target_accept` or reparameterize.
There were 282 divergences after tuning. Increase `target_accept` or reparameterize.
The acceptance probability does not match the target. It is 0.8848443240050202, but should be close to 0.8. Try to increase the number of tuning steps.
The estimated number of effective samples is smaller than 200 for some parameters.
```

The problem appears to be that in the diverging samples, one element of **bad_beta** jumps to a logodds that is close to (but less than) the value 19.0

```python
def max_bad_beta(warning):
    return np.amax(warning.extra['bad_beta_logodds__'])

def logodds_and_beta(value):
    return value, pm.transforms.logodds.backward(value).eval()[()]

def maxs_from_warnings(trace, limit=50):
    warnings = trace.report._warnings[:limit]
    return [logodds_and_beta(max_bad_beta(warning)) for warning in warnings]

maxs_from_warnings(bad_trace)
[(18.522285926243683, 0.9999999909661387),
 (18.026951801202443, 0.9999999851750137),
 (18.273787751452954, 0.9999999884176999),
 (15.811521213093858, 0.9999998641237577),
 (18.788894703456123, 0.999999993080309),
 (17.840933189508505, 0.9999999821441242),
 (18.99068873589819, 0.9999999943447908),
 (18.650396555754487, 0.9999999920524058),
 (18.886465782831156, 0.9999999937235782),
 (18.614120566380194, 0.9999999917588059),
 (18.748619470023584, 0.9999999927959284),
 (18.96328594127111, 0.9999999941876794),
 (18.43516905323891, 0.9999999901438387),
 (18.7824011307429, 0.9999999930352292),
 (18.61426914065103, 0.9999999917600301),
 (18.61426914065103, 0.9999999917600301),
 (18.959200871340606, 0.9999999941638871),
 (18.310579256420056, 0.9999999888360865),
 (18.875771090438388, 0.9999999936560935),
 (18.419609630862556, 0.9999999899892832),
 (18.743196196992155, 0.9999999927567527), 
...
]
```

What is special about 19? Note that **good_beta** generates logodds close to -19.0 as often as **bad_beta** generates logodds close to 19.0, but **good_beta** never diverges.

## Versions and main components

* PyMC3 Version: 3.9.1
* Theano Version: 1.0.4
* Python Version: 3.8.3
* Operating system: macOS 10.15.16
* How did you install PyMC3: conda

**Comment by twiecki** [comment]
![image](https://user-images.githubusercontent.com/674200/91172109-f0c6ad00-e6db-11ea-8802-c2cd12eabf53.png)
What magic is this :-O.

**Comment by twiecki** [comment]
CC @brandonwillard

**Comment by bridgeland** [comment]
@AlexAndorra: to be fair @aseyboldt [tracked the problem through the codebase](https://discourse.pymc.io/t/good-results-but-many-divergent-samples-what-me-worry/5655/14), not me.

**Comment by AlexAndorra** [comment]
Don't be too harsh on yourself: you did quite a nice investigative debugging work too 😉

**Comment by bridgeland** [comment]
Over in [discourse](https://discourse.pymc.io/t/good-results-but-many-divergent-samples-what-me-worry/5655/14), @aseyboldt wrote:

This does seem to be a theano issue at the root:
The sigmoid implementation is a bit strange:

```python
            return """%(z)s = %(x)s < -709.0 ? 0.0 : %(x)s > 19.0 ? 1.0 : 1.0 /(1.0+exp(-%(x)s));""" % locals()
```

Why 19? That expression evaluates to something different from 1 until ~36.6.
And then on top of that the stability enhancing code seems to work in the case of log1p(-sigmoid(x)):

```python
import theano
import theano.tensor as tt

x_ = theano.tensor.dscalar('x')
x_.tag.test_value = np.array(1., dtype='d')
f = theano.function([x_], tt.log(tt.nnet.sigmoid(x_)))
g = theano.function([x_], tt.log1p(-tt.nnet.sigmoid(x_)))
theano.printing.debugprint(f)
theano.printing.debugprint(g)
Elemwise{Composite{(-scalar_softplus((-i0)))}} [id A] ''   0
 |x [id B]
Elemwise{Composite{log1p((-scalar_sigmoid(i0)))}} [id A] ''   0
 |x [id B]
```

Even though both supposedly should be using softplus:

```python
424:log1p_neg_sigmoid = gof.PatternSub(
425-    (tensor.log1p,
426-     (tensor.neg, (sigmoid, 'x'))),
427-    (tensor.neg, (softplus, 'x')),
428-    values_eq_approx=values_eq_approx_remove_inf,
429-    allow_multiple_clients=True)
```

----------

And he further added:

On top of that, the pymc impl of invlogit doesn’t seem that great either:

```python
def invlogit(x, eps=sys.float_info.epsilon):
    """The inverse of the logit function, 1 / (1 + exp(-x))."""
    return (1.0 - 2.0 * eps) / (1.0 + tt.exp(-x)) + eps
```

Theano has its own ideas about what to do with this:

```python
h = theano.function([x_], pm.math.invlogit(x_))
theano.printing.debugprint(h)
Elemwise{Composite{(i0 + (scalar_sigmoid(i1) * i2))}} [id A] ''   0
 |TensorConstant{2.22044604..250313e-16} [id B]
 |x [id C]
 |TensorConstant{0.9999999999999996} [id D]
```

We should fix the theano sigmoid and use that in invlogit directly I think…

**Comment by bridgeland** [comment]
The 19.0 expression is in **ScalarSigmoid.c_code()**, found in 
theano/tensor/nnet/sigm.py. The whole method is defined as:

```python
    def c_code(self, node, name, inp, out, sub):
        (x,) = inp
        (z,) = out
        # We add boundary checks prevent exp from generating inf or
        # 0. The reset of the logic always generate 0 or 1 in those
        # cases. This is a speed optimization.
        # The constants were obtained by looking at the output of
        # python commands like:
        #
        # import numpy, theano
        # dt='float32'  # or float64
        # for i in range(750):
        #     print i, repr(theano._asarray(1.0, dtype=dt) /
        #                   (theano._asarray(1.0, dtype=dt) +
        #                    numpy.exp(-theano._asarray([i,-i], dtype=dt))))

        # float16 limits: -11.0, 7.0f
        # We use the float32 limits for float16 for now as the
        # computation will happen in float32 anyway.
        if (
            node.inputs[0].type == scalar.float32
            or node.inputs[0].type == scalar.float16
        ):
            return (
                """%(z)s = %(x)s < -88.0f ? 0.0 : %(x)s > 15.0f ? 1.0f : 1.0f /(1.0f + exp(-%(x)s));"""
                % locals()
            )
        elif node.inputs[0].type == scalar.float64:
            return (
                """%(z)s = %(x)s < -709.0 ? 0.0 : %(x)s > 19.0 ? 1.0 : 1.0 /(1.0+exp(-%(x)s));"""
                % locals()
            )
        else:
            raise NotImplementedError("only floatingpoint is implemented")
```

So it seems the mystery 19.0 is an optimization, determined empirically
by checking when **numpy.exp()** hits 1.0 rather than something a bit
short of 1.0.

Running the experiment in the comment yields a slightly different result,
with an overflow above 21, not 19:

![image](https://user-images.githubusercontent.com/5245697/91299500-b149a080-e76f-11ea-9e0d-9e3917cdf5a3.png)

And the experiment is flawed, mistaking the precision of printing a 
floating point with the underlying precision of the floating point. When
the print precision is increased, the true limit is revealed as 36, not 19:

![image](https://user-images.githubusercontent.com/5245697/91299862-4cdb1100-e770-11ea-95df-db3a204dc765.png)

So one easy fix is to change 

```python
        elif node.inputs[0].type == scalar.float64:
            return (
                """%(z)s = %(x)s < -709.0 ? 0.0 : %(x)s > 19.0 ? 1.0 : 1.0 /(1.0+exp(-%(x)s));"""
                % locals()
            )
```
to
```python
        elif node.inputs[0].type == scalar.float64:
            return (
                """%(z)s = %(x)s < -709.0 ? 0.0 : %(x)s > 36.0 ? 1.0 : 1.0 /(1.0+exp(-%(x)s));"""
                % locals()
            )
```

**Comment by bridgeland** [comment]
Although  it is possible I do not really understand the issue. Maybe the communication
of tensor values between python and C occurs through their standard string repr rather than the 
underlying representation in memory. In that case the original experiment is not flawed.

**Comment by brandonwillard** [comment]
The method `Op.c_code` populates the argument `inp` with names for the actual input variables&mdash;in a `gensym`-like way.  In other words, the numerical input values&mdash;aside from the ones in the conditional expressions&mdash;aren't represented in string/`repr` form, if that's what you meant.

**Comment by aseyboldt** [comment]
I did some experiments, and I don't think that the shortcut for very small
or large values is worth the cost (at least for double, this might be
different for float or even float16).
If you want to try this on your machine, the notebook is here:
https://gist.github.com/aseyboldt/0f93a60085183980bb18a1d1ecad4021

The check if x is an extreme value adds some costs for values where it
doesn't fit, and saves an exp evaluation if it does. Such extreme values
should be rather rare I think.
While experimenting I noticed that it really makes a difference if we use a
vectorized exp or a scalar exp. gcc is able to produce vectorized exp code
(libmvec), but it requires some rather extreme compiler args. (or I think
some openmp simd pragma...)
The speed difference on my laptop is huge though (~60ms vs ~13ms).
I thought maybe the if statement would prevent vectorization completely,
but gcc seems to be smart enough, so that the vectorized if-version is only
slightly slower than the vectorized non-if version (16ms vs 13ms).

Summary:
- I think we should not bother with the x < -700, x > 36 shortcut at all
and just use 1/(1 + exp(-x)), this is what numpy does by the way.
- If we want to improve performance of expit by a large margin, we should
investigate how we can make sure theano produces code that is vectorized.

**Comment by bridgeland** [comment]
@aseyboldt Eliminating the broken optimization is a much better solution than fixing it. Kudos to you.

How does it work now? Who makes it so?

**Comment by twiecki** [comment]
want to do a PR David?

**Comment by bridgeland** [comment]
I will try, against my better judgment. 

Step 1: install Xcode

**Comment by bridgeland** [comment]
(Lack of) progress report: I started with a fork, clone, and local install. Then I ran the 
theano tests, before making any changes.  

Running the 2393 tests took 2 hours, and resulted in 654 errors and 28 failures. Wups!

I suspect someone who already understands theano should do this.

**Comment by bridgeland** [comment]
I have made no progress on the 654 errors. Obviously something is not properly
installed in my local machine. But I do not know what.  

@twiecki, @brandonwillard, @aseyboldt, @AlexAndorra: Help me Obi-Wan 
Kenobi; you're my only hope.

**Comment by bridgeland** [comment]
Or perhaps I am misunderstanding the situation. Perhaps the theano tests are no 
longer maintained, and a great many errors are to be expected.

**Comment by brandonwillard** [comment]
@bridgeland, if you submit a draft PR, we can help debug it.

**Comment by bridgeland** [comment]
@brandonwillard Done. But the PR is entirely untested, due to aforementioned issues in 
setting up a local theano dev environment.

**Comment by bridgeland** [comment]
Update: I still am not able to run the theano tests. But I was able to install pymc3 (v3.9.3) 
and run the same test of betas shown above. With the fix, there are 40X fewer divergences.
