### ISSUE TITLE
Remove theano.dot

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#52]
The `__init__.py`-level `theano.dot` function is awkward and&mdash;as far as I can tell&mdash;completely unnecessary.  What it appears to be doing is supposed to be done in class-level implementations of `__dot__` and `__rdot__` (e.g. an interface/mixin class that checks both objects for the appropriate methods).

This function should be removed and the classes that implement `__dot__` and `__rdot__` (e.g. `theano.tensor.var._tensor_py_operators`) should handle this.

**Comment by twiecki** [comment]
But there is still `tt.dot(x, y)` then, right? Or only `x.dot(y)`?

**Comment by brandonwillard** [comment]
There's already a distinct `theano.tensor.basic.dot` function on top of the class-level `_tensor_py_operators.dot` method, which makes this `theano.dot` all the more confusing.

**Comment by twiecki** [comment]
Yep it really does.

**Comment by eigenfoo** [comment]
I'd be interested in taking this on, but am unclear on some things.

> What it appears to be doing is supposed to be done in class-level implementations of `__dot__` and `__rdot__` (e.g. an interface/mixin class that checks both objects for the appropriate methods).

Please correct me if I'm wrong: Theano tensors derive a lot of operators (addition, comparisons, etc.) via mixin classes, for example the [`theano.tensor.var._tensor_py_operators` class](https://github.com/pymc-devs/Theano-PyMC/blob/008579b56901c0e228ac26e04c1e39ebb34545ca/theano/tensor/var.py#L17). `theano.dot` is barely used, but once it's gone the only way to take dot products will be with these mixins.

If my understanding is right, I have two questions to make sure I can check that I'm not deprecating dot products (links would be appreciated!):

1. How many mixin classes are there that supply tensor operators?
1. How many different kinds/classes of Theano tensors are there? Do they all use the same mixins?

**Comment by brandonwillard** [comment]
I think that's _the_ mixin, other than its subset clone: `theano.sparse.basic._sparse_py_operators`.  

While I'm thinking about it, we should either use a single mixin for both&mdash;with some overrides, if necessary&mdash;or break `theano.tensor.var._tensor_py_operators` apart so that its shared methods can be used by both the sparse and non-sparse types.  Really, **the sparse tensors should use exactly the same interfaces/types (and much of the same code) as the dense tensors**, since we're supposed to be modeling high-level tensors with these interfaces, and **not** their implementation details.  (This needs to become its own issue.)

Anyway, my impression is that `theano.dot` can be removed/replaced with versions of `theano.tensor.var.[_tensor_py_operators | _sparse_py_operators].__dot__` that worked like the built-in dunder methods (e.g. have them return `NotImplemented` and add logic that checks `__rdot__` in such cases).
