### ISSUE TITLE
Move Theano Type instance definitions

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#53]
The modules `theano.tensor.basic` and `theano.scalar.basic` contain numerous type definitions (e.g. `TensorType("float32", (True, False))`).  These are more appropriately defined in their respective `type.py` modules (e.g. where `TensorType` itself is defined).  Currently, they're just creating unnecessary dependencies between said types and those very large `basic.py` modules.

**Comment by canyon289** [comment]
To double check are we referring to lines like this?
https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/scalar/basic.py#L730

or these

https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/scalar/basic.py#L899

That should be moved to their respective type.py modules?

**Comment by brandonwillard** [comment]
Yes, both of those examples look like the definitions I'm talking about.  

It's just weird that we would require loading/referencing huge modules like `theano.[tensor|scalar].basic` just to get instances of types that are defined in other files.

**Comment by canyon289** [comment]
Agree, will start refactoring these

**Comment by canyon289** [comment]
For anyone else that would like to try this issue ticket, here is a PR I started with helpful comments from Brandon and others. Check it over to get more information and perhaps use it as a starting point https://github.com/pymc-devs/Theano-PyMC/pull/180
