### ISSUE TITLE
Rename scalar and tensor maximum and minimum Ops

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#55]
There are distinct `maximum` and `minimum` `Op`s in both `theano.scalar.basic` and `theano.tensor.basic`.  It seems like we could give these different names and avoid the confusion and potential for bugs.

**Comment by michaelosthege** [comment]
Do you mean to rename both? (To "Max" and "Min"?)

The way how I understand this docstring, the tensor Op is created from the scalar Op with the same name:

```
def _scal_elemwise_with_nfunc(nfunc, nin, nout):
    """
    Replace a symbol definition with an elementwise version of the
    corresponding scalar Op.  If it is not None, the nfunc argument
    should be a string such that getattr(numpy, nfunc) implements
    a vectorized version of the elemwise operation. nin is the number
    of inputs expected by that function, and nout is the number of
    **destination** inputs it takes. That is, the function should
    take nin+nout inputs. nout == 0 means that the numpy function
    does not take a numpy array argument to put its result in.

    """
```
...
```
_scal_elemwise = _scal_elemwise_with_nfunc(None, None, None)
```

...

```
@_scal_elemwise
def maximum(x, y):
    """elemwise maximum. See max for the maximum in one tensor"""
    # see decorator for function body
```

(all three code blocks are from tensor/basic.py)

**Comment by brandonwillard** [comment]
Yes, `theano.tensor.basic.[minimum|maximum]` are just `Elemwise`s `Op`s for the scalar `Op`s `theano.scalar.basic.[minimum|maximum]`.

This issue is simply recommending that we&mdash;for instance&mdash;prefix the scalar `Op`s with something like `scalar_*`, because reading the code and `str` outputs for `Op`s with name clashes like this can be unnecessarily confusing.

This isn't a user-level annoyance as much as a developer-level one.
