### ISSUE TITLE
Turn theano.compat into a module

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#57]
Currently, `theano.compat` is a sub-package containing only an `__init__.py` file.  The `__init__.py` file should be renamed to `compat.py`, moved into the `theano` directory/package, and the old `compat` directory should be deleted.

**Comment by Rashmi-K-A** [comment]
Hi @brandonwillard, can I take this one?

**Comment by twiecki** [comment]
@Rashmi-K-A Definitely, thanks for offering your help!
