### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#63]
If I'm not mistaken, we can run more jobs in parallel using GitHub Actions and speed up these tests.  For that reason&mdash;and some others (e.g. we can easily perform our deployment automations in Actions, as well), let's switch from Travis to GitHub Actions.

**Comment by dfm** [comment]
I'm happy to help with this! A little buried under work this week, but I'll try to put in some time soon if someone else doesn't get there first.

**Comment by twiecki** [comment]
@dfm That'd be greatly appreciated. Did you see the JAX stuff? Quite exciting developments!
