### ISSUE TITLE
ImportError with PyMC3

### ISSUE THREAD

**Issue by michaelosthege** [pymc-devs/Theano-PyMC#64]
With latest PyMC3 master and Theano-PyMC master, I still get an import error:

![image](https://user-images.githubusercontent.com/5894642/94588791-ae693080-0284-11eb-83b5-f9417c4bc808.png)

Just `import theano` is fine..
Should it be a PyMC3 ticket?

**Comment by michaelosthege** [comment]
nevermind - this was actually still PyMC3 3.9.1

**Comment by brandonwillard** [comment]
FYI: there were import errors that were just recently resolved in #58.
