### ISSUE TITLE
Merge RandomVariable Ops

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#66]
The Symbolic PyMC project contains a [base `RandomVariable` `Op`](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/theano/ops.py#L75) with advanced shape-handling logic and a more optimization-friendly form, as well as implementations for [many common random variable types](https://github.com/pymc-devs/symbolic-pymc/blob/master/symbolic_pymc/theano/random_variables.py).  We should merge/replace the current [`RandomFunction` `Op`](https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/tensor/raw_random.py#L107) with `RandomVariable` (and the related [`rng_mrg`](https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/sandbox/rng_mrg.py implementations).

There's also [`RandomStreams`](https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/tensor/shared_randomstreams.py) class that should be considered/made to work with `RandomVariable`.

**Comment by twiecki** [comment]
This would be an incredible mile-stone to hit.

**Comment by michaelosthege** [comment]
Was this closed by #131 or #137 ?
