### ISSUE TITLE
Implement JAX conversion for Scan Op

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#69]
The Theano [`Scan` `Op`](https://github.com/pymc-devs/Theano-PyMC/blob/1a9b04bfe480b758ddfa54ba49c88bee3bec419c/theano/scan/op.py#L80) currently has an incomplete implementation.  We need to finish that, especially since this `Op` is an important bridge to a lot of valuable JAX functionality and future performance enhancements.

There's already [a (skipped) test for this conversion](https://github.com/pymc-devs/Theano-PyMC/blob/1a9b04bfe480b758ddfa54ba49c88bee3bec419c/tests/sandbox/test_jax.py#L267) that builds a `Scan` `Op` and its equivalent `jax.lax.scan`.  This should provide a good start for anyone wanting to get involved.  Plus, the [current partial implementation](https://github.com/pymc-devs/Theano-PyMC/blob/1a9b04bfe480b758ddfa54ba49c88bee3bec419c/theano/sandbox/jaxify.py#L385) already provides the necessary framework for the conversion.  All that's needed is for someone to finish bridging the inputs and outputs.

**Comment by eigenfoo** [comment]
Is this issue still relevant? If so, I'd be interested in taking this on.

The links have either broken or point to different lines than they originally did - for long-standing issues, it would be nice if we could link to lines/files at a specific commit, instead of a branch (which could change with subsequent commits).

**Comment by junpenglao** [comment]
I started working on this - will try to finish this tomorrow.
assigning it to myself.

**Comment by brandonwillard** [comment]
@junpenglao, do you mind setting up a draft PR?  This work is a great means of learning about `Scan`, and it might help @eigenfoo and others if they could follow its progress.
