### ISSUE TITLE
Simplify/combine status checks

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#87]
Our CI workflow sets up a bunch of independent jobs via the matrix settings, and each one of those creates a possible status check under this repo's branch protection settings.  It would be better if we had a single job that could serve as a status check for all the matrix jobs, especially as we add/remove jobs via the matrix settings (e.g. new Python versions).

So far, [this](https://github.community/t/status-check-for-a-matrix-jobs/127354/7?u=brandonwillard) was the best advice I could find; it says to create a new job that simply checks the matrix build status.

**Comment by brandonwillard** [comment]
Also, after adding the file filters to the workflow in #83, it looks like there are perpetually uncompleted checks.  Is there any way around that?

**Comment by dfm** [comment]
Good - I think I can work out the logic for all this!
