### ISSUE TITLE
Conda-forge build is broken on import test

### ISSUE THREAD

**Issue by twiecki** [pymc-devs/Theano-PyMC#91]
```
import: 'theano.compile'
import: 'theano.compile.sandbox'
import: 'theano.compile.tests'
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/theano-pymc_1602124543407/test_tmp/run_test.py", line 11, in <module>
    import theano.compile.tests
```

from https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=219395&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=841356e0-85bb-57d8-dbbc-852e683d1642&l=2075

This happens because the recipe tests all kinds of imports: https://github.com/pymc-devs/Theano-PyMC/blob/master/conda/meta.yaml#L32

**Comment by brandonwillard** [comment]
Looks like we need to change something in https://github.com/conda-forge/theano-pymc-feedstock.

**Comment by brandonwillard** [comment]
Yeah, it looks like `meta.yaml` should just run `pytest` instead of [loading a bunch of test modules](https://github.com/conda-forge/theano-pymc-feedstock/blob/master/recipe/meta.yaml#L32) (which are now located in a separate `tests` directory).

**Comment by dfm** [comment]
I think that it's generally recommended to just test that `import` works on conda-forge rather than running the full test suite. But yes, that's where it should be fixed, not here!

**Comment by brandonwillard** [comment]
> I think that it's generally recommended to just test that `import` works on conda-forge rather than running the full test suite.

That sounds _much_ better.

**Comment by twiecki** [comment]
It is just testing the import.

**Comment by dfm** [comment]
Right, but @brandonwillard was suggesting otherwise :D

**Comment by brandonwillard** [comment]
I just put in a PR that will hopefully close this: https://github.com/conda-forge/theano-pymc-feedstock/pull/3.

**Comment by brandonwillard** [comment]
@twiecki @ericmjl, that PR seems to do the job.  It needs a review and merge, though.

**Comment by brandonwillard** [comment]
Closing this now that https://github.com/conda-forge/theano-pymc-feedstock/pull/3 is merged.
