### ISSUE TITLE
Document/Email that announce Theano-PyMC

### ISSUE THREAD

**Issue by nouiz** [pymc-devs/Theano-PyMC#92]
Hi,

I recall seeing an email/url that annonce Theano-PyMC fork, but I do not find it. Does it really exist? If so, it would be good to link to it from the README in this repo.

**Comment by twiecki** [comment]
This one? https://groups.google.com/g/theano-users/c/RRqAgfLRd78

**Comment by nouiz** [comment]
It was that one. I didn't expect JAX in the title :)
Thanks.
