### ISSUE TITLE
Refactor theano.config

### ISSUE THREAD

**Issue by brandonwillard** [pymc-devs/Theano-PyMC#94]
I've recently noticed that the config system&mdash;operating mostly from the file [`theano.configdefaults`](https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/configdefaults.py)&mdash;introduces a considerable tangle of import dependencies.  

For instance, the `theano.config` object is created when `theano/__init__.py` is loaded, and from there it attempts to do all sorts of config value validation, and this validation explicitly (and perhaps _unnecessarily_) requires that a large amount of actual class objects be loaded immediately (e.g. everything from `theano.compile.mode`, which itself requires other `theano.config` values to load, as well as all the linkers objects from `theano.gof.*`, etc.)  This triggers further imports for modules with overly strict `theano.config`-dependent top-level conditions (e.g. [here](https://github.com/pymc-devs/Theano-PyMC/blob/master/theano/gof/vm.py#L694) a class definition itself is dependent on the value of `theano.config.cxx`!)

If anything, these module-level dependencies on `theano.config` shouldn't be necessary and/or as pervasive as they currently are.

Furthermore, aren't there well established config-file libraries we can use instead of maintaining our own?

_Originally posted by @brandonwillard in https://github.com/pymc-devs/Theano-PyMC/issue_comments/705671530_

**Comment by michaelosthege** [comment]
I was shocked to see that `configdefaults.py`+`configparser.py` are a 2_800 line monstrosity, but I believe it's an important contribution to clean it up.

So I'm willing to take this issue..

@brandonwillard:
- how open are we to breaking support with previous config file/flag features?
- `test_config.py` is 45 lines and the test suite does not seem to include a single config file to test with. Do you have some configs lying around that could serve as test inputs for the parser?
- I would try to refactor the entire thing into using the config parser from the Python standard library. _Maybe_ with some inspiration from Airflow?
- For the vast majority of PyMC3 use cases, one doesn't even touch the Theano config - can we conclude that we don't need most of them?

**Comment by brandonwillard** [comment]
> * how open are we to breaking support with previous config file/flag features?

We'll have to determine that on a case-by-case basis, because it really depends on exactly what we're planning to break.  In general, I don't mind changing the interface or something similar, though.

> * `test_config.py` is 45 lines and the test suite does not seem to include a single config file to test with. Do you have some configs lying around that could serve as test inputs for the parser?

If we can test functionality directly (i.e. not indirectly via a parsed file), then we should definitely do that.  Also, we can craft configs as strings within tests and keep things much more self-contained.

> * I would try to refactor the entire thing into using the config parser from the Python standard library. _Maybe_ with some inspiration from Airflow?

That would be perfect!  And a big _maybe_ on the Airflow inspiration; I've dealt with enough of that to not want any more (e.g. [here](https://github.com/pulls?q=airflow+is%3Apr+author%3Abrandonwillard+archived%3Afalse+sort%3Aupdated-desc)).


> * For the vast majority of PyMC3 use cases, one doesn't even touch the Theano config - can we conclude that we don't need most of them?

There are quite a few important settings in there, so I don't think we can draw that conclusion.  Regardless, there aren't _that_ many options to implement, so it shouldn't be too much effort.
